# .github/actions/setup-python-poetry/action.yml
name: 'Setup Python and Poetry'
description: 'Sets up Python and Poetry with caching'

inputs:
  python-version:
    description: 'Python version to use'
    required: true
  poetry-version:
    description: 'Poetry version to use'
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
    
    - uses: abatilo/actions-poetry@v3
      with:
        poetry-version: ${{ inputs.poetry-version }}
    
    - name: Setup Poetry cache
      shell: bash
      run: |
        poetry config virtualenvs.in-project true
    
    - uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ inputs.python-version }}-${{ hashFiles('**/poetry.lock') }}